allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tag
parameters:
  chargetype: Daily
  type: SSD3.0
  tags: "key1:value1,key2:value2,key3:value3,key4:value4"
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: Immediate