apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-csi-provisioner
provisioner: com.ksc.csi.diskplugin
allowVolumeExpansion: true
parameters:
  type: SSD3.0
  # region: cn-beijing-6
  # zone: cn-beijing-6a
  chargetype: Daily
  purchasetime: "10"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: js-csi-diskplugin
    meta.helm.sh/release-namespace: miks
  labels:
    app.kubernetes.io/managed-by: Helm
  name: js-sc
parameters:
  chargetype: Daily
  region: eu-east-1
  tags: cop.xiaomi_owt.inf_pdl.miks.miks-cluster~mos1-serving-k8s
  type: SSD3.0
  zone: eu-east-1a
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: Immediate