apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kfsplugin
  resources:
    requests:
      storage: 20Gi