apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 80
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
            - name: www1
              mountPath: /usr/share/nginx/html1
  volumeClaimTemplates:
    - metadata:
        name: www
        labels:
          csi-epc: test
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: kfsplugin
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: www1
        labels:
          csi-epc: test
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: kfsplugin
        resources:
          requests:
            storage: 5Gi