FROM hub.kce.ksyun.com/ksyun/centos

LABEL maintainers="gaohong1@kingsoft.com"

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN  yum install xfsprogs e2fsprogs -y 

COPY bin/csi-diskplugin /csi-diskplugin

ENTRYPOINT ["/csi-diskplugin"]
