allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kingsoftcloud-disk-hour
parameters:
  chargetype: HourlyInstantSettlement
  type: SSD3.0 #SSD3.0,ESSD_PL0,ESSD_PL1,ESSD_PL2,ESSD_PL3,EHDD
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer