apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: kingsoftcloud-disk
---
apiVersion: v1
kind: Pod
metadata:
  name: test-disk
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: disk-pvc
          mountPath: "/data"
  volumes:
    - name: disk-pvc
      persistentVolumeClaim:
        claimName: disk-pvc
