{{- if semverCompare "<=1.17" .Capabilities.KubeVersion.Version -}}
apiVersion: storage.k8s.io/v1beta1
{{- else -}}
apiVersion: storage.k8s.io/v1
{{- end }}
kind: CSIDriver
metadata:
  name: com.ksc.csi.diskplugin
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
---
{{- if semverCompare "<=1.17" .Capabilities.KubeVersion.Version -}}
apiVersion: storage.k8s.io/v1beta1
{{- else -}}
apiVersion: storage.k8s.io/v1
{{- end }}
kind: CSIDriver
metadata:
  name: com.ksc.csi.nfsplugin
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
{{- if semverCompare ">1.17" .Capabilities.KubeVersion.Version }}    
  fsGroupPolicy: File
{{- end }}
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: com.ksc.csi.ks3plugin
spec:
  attachRequired: false
  podInfoOnMount: true