kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-diskplugin
  namespace: {{ .Values.app.image.namespace }}
spec:
  selector:
    matchLabels:
      app: csi-diskplugin
  template:
    metadata:
      labels:
        app: csi-diskplugin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: NotIn
                  values:
                    - virtual-kubelet
      priorityClassName: {{ .Values.app.priorityClassName }}
      serviceAccount: csi-diskplugin-sa
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
        - args:
          - --v=5
          - --csi-address=$(ADDRESS)
          - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
          env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: DRIVER_REG_SOCK_PATH
            value: {{ .Values.kubeletDir }}/plugins/com.ksc.csi.nfsplugin/csi.sock
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: {{ include "imageSpec" (list .Values.app.image "pluginRegistrar") }}
          imagePullPolicy: IfNotPresent
          name: nfs-driver-registrar
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
          - mountPath: /csi
            name: nfsplugin-dir
          - mountPath: /registration
            name: registration-dir
        - name: disk-driver-registrar 
          imagePullPolicy: IfNotPresent
          image: {{ include "imageSpec" (list .Values.app.image "pluginRegistrar") }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ .Values.kubeletDir }}/plugins/com.ksc.csi.diskplugin/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: diskplugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: ks3-driver-registrar
          imagePullPolicy: IfNotPresent
          image: {{ include "imageSpec" (list .Values.app.image "pluginRegistrar") }}

          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ .Values.kubeletDir }}/plugins/com.ksc.csi.ks3plugin/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: ks3plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: csi-diskplugin
          image: {{ include "imageSpec" (list .Values.app.image "plugin") }}
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--node-server=true"
            - "--controller-server=false"
            # - "--v=2"
            # - "--metric=false"
            # - "--max-volumes-pernode=8"
          {{- range $key, $value := .Values.extraArgs.ds }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          env:       
            - name: CSI_ENDPOINT
              value: unix:/{{ .Values.kubeletDir }}/plugins/com.ksc.csi.driverplugin-replace/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: AKSK_CONF
              valueFrom:
                configMapKeyRef:
                  key: aksk-conf
                  name: csi-aksk-conf
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: pods-mount-dir
              mountPath: {{ .Values.kubeletDir }}/
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            - name: aksk
              mountPath: /var/lib/aksk
            - name: launcher-socket-dir
              mountPath: /tmp
              mountPropagation: "Bidirectional"
      volumes:
      - hostPath:
          path: {{ .Values.kubeletDir }}/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: {{ .Values.kubeletDir }}/plugins/com.ksc.csi.diskplugin/
          type: DirectoryOrCreate
        name: diskplugin-dir
      - hostPath:
          path: {{ .Values.kubeletDir }}/plugins/com.ksc.csi.nfsplugin/
          type: DirectoryOrCreate
        name: nfsplugin-dir
      - hostPath:
          path: {{ .Values.kubeletDir }}/plugins/com.ksc.csi.ks3plugin/
          type: DirectoryOrCreate
        name: ks3plugin-dir
      - hostPath:
          path: {{ .Values.kubeletDir }}/
          type: Directory
        name: pods-mount-dir
      - hostPath:
          path: /dev/
          type: ""
        name: device-dir
      - name: aksk
        configMap:
          name: user-temp-aksk
      - name: launcher-socket-dir
        hostPath:
          path: /etc/csi-ks3
          type: DirectoryOrCreate
