apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-deployment
  labels:
    app: ssd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
  template:
    metadata:
      labels:
        app: ssd
    spec:
      containers:
        - name: nginx
          image: hub.kce.ksyun.com/yimenghua/nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: ssd
              mountPath: /usr/share/nginx/html
      volumes:
        - name: ssd
          persistentVolumeClaim:
            claimName: ssd

