apiVersion: apps/v1
kind: Deployment
metadata:
  name: wffc-essd-deployment
  labels:
    app: wffc-essd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wffc-essd
  template:
    metadata:
      labels:
        app: wffc-essd
    spec:
      containers:
        - name: nginx
          image: hub.kce.ksyun.com/yimenghua/nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: wffc-essd
              mountPath: /usr/share/nginx/html
      volumes:
        - name: wffc-essd
          persistentVolumeClaim:
            claimName: wffc-essd

