allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: essd
parameters:
  chargetype: Daily
  type: ESSD_PL0
#  zone: cn-beijing-6e
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: Immediate