apiVersion: apps/v1
kind: Deployment
metadata:
  name: wffc-deployment
  labels:
    app: wffc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wffc
  template:
    metadata:
      labels:
        app: wffc
    spec:
      containers:
        - name: nginx
          image: hub.kce.ksyun.com/yimenghua/nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: wffc
              mountPath: /usr/share/nginx/html
      volumes:
        - name: wffc
          persistentVolumeClaim:
            claimName: wffc

