allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wffc-allow
parameters:
  chargetype: Daily
  type: SSD3.0
#  zone: cn-beijing-6a
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
    - key: com.ksc.csi.node/disktype.EHDD
      values:
        - available
    - key: failure-domain.beta.kubernetes.io/zone
      values:
        - cn-beijing-6a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wffc-allow
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wffc-allow
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  wffc-allow-deployment
  labels:
    app:  wffc-allow
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  wffc-allow
  template:
    metadata:
      labels:
        app:  wffc-allow
    spec:
      containers:
        - name: nginx
          image: hub.kce.ksyun.com/yimenghua/nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name:  wffc-allow
              mountPath: /usr/share/nginx/html
      volumes:
        - name:  wffc-allow
          persistentVolumeClaim:
            claimName:  wffc-allow