---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-controller
      role: csi-do
  serviceName: "csi-do"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-controller
        role: csi-do
    spec:
      priorityClassName: system-node-critical
      serviceAccount: csi-controller-sa
      containers:
        - args:
            - --feature-gates=Topology=true
            - --csi-address=$(ADDRESS)
            - --v=2
            - --timeout=20s
            - --retry-interval-start=2s
            - "--volume-name-prefix=kfs"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/com.ksc.csi.nfsplugin/csi.sock
          image: hub.kce.ksyun.com/ksyun/csi-provisioner:v2.2.2-mp
          imagePullPolicy: IfNotPresent
          name: csi-nfs-provisioner
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/com.ksc.csi.nfsplugin/
              name: nfs-socket-dir
        - name: csi-disk-provisioner
          image: hub.kce.ksyun.com/ksyun/csi-provisioner:v2.2.2-mp
          args:
            - "--feature-gates=Topology=true"
            - "--csi-address=$(ADDRESS)"
            - "--v=2"
            - "--timeout=30s"
            - "--retry-interval-start=3s"
            - "--leader-election=true"
            - "--leader-election-namespace=kube-system"
            - "--volume-name-prefix=disk"
            - "--extra-create-metadata=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/com.ksc.csi.diskplugin/csi.sock
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: disk-socket-dir
              mountPath: /var/lib/csi/sockets/com.ksc.csi.diskplugin/
        - name: csi-disk-attacher
          image:  hub.kce.ksyun.com/ksyun/csi-attacher:v3.2.1-mp
          args:
            - "--v=2"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=20s"
            - "--retry-interval-start=2s"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/com.ksc.csi.diskplugin/csi.sock
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: disk-socket-dir
              mountPath: /var/lib/csi/sockets/com.ksc.csi.diskplugin/
        - name: csi-disk-resizer
          imagePullPolicy: IfNotPresent
          image:  hub.kce.ksyun.com/ksyun/csi-resizer:v1.2.0-mp
          args:
            - "--v=2"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=20s"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/com.ksc.csi.diskplugin/csi.sock
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: disk-socket-dir
              mountPath: /var/lib/csi/sockets/com.ksc.csi.diskplugin/
        - args:
            - --endpoint=$(CSI_ENDPOINT)
            - --driver=com.ksc.csi.diskplugin,com.ksc.csi.nfsplugin
            - --v=2
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/com.ksc.csi.driverplugin-replace/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: AKSK_CONF
              valueFrom:
                configMapKeyRef:
                  key: aksk-conf
                  name: csi-aksk-conf
          image: hub.kce.ksyun.com/ksyun/csi-diskplugin:1.9.1-amd64-open
          imagePullPolicy: Always
          name: csi-diskplugin
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: pods-mount-dir
            - mountPath: /var/lib/csi/sockets/com.ksc.csi.diskplugin/
              name: disk-socket-dir
            - mountPath: /var/lib/csi/sockets/com.ksc.csi.nfsplugin/
              name: nfs-socket-dir
            - mountPath: /var/lib/aksk
              name: aksk
      volumes:
        - emptyDir: {}
          name: disk-socket-dir
        - emptyDir: {}
          name: nfs-socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: pods-mount-dir
        - secret:
            secretName: kce-security-token
          name: aksk
