---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: com.ksc.csi.diskplugin
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: com.ksc.csi.nfsplugin
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File
