apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: com.ksc.csi.diskplugin
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes: # added in Kubernetes 1.16, this field is beta
    - Persistent