########################################
###########                 ############
###########   Node plugin   ############
###########                 ############
#######################################

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-diskplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-diskplugin
  template:
    metadata:
      labels:
        app: csi-diskplugin
        role: csi-do
    spec:
      serviceAccount: csi-diskplugin-sa
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: hub.kce.ksyun.com/ksyun/csi-node-driver-registrar:v2.2.0
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--plugin-registration-path=/registration"
            - "--kubelet-registration-path=/data/kubelet/plugins_registry/com.ksc.csi.diskplugin/csi.sock"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /data/kubelet/plugins_registry/com.ksc.csi.diskplugin/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: csi-diskplugin
          image: hub.kce.ksyun.com/ksyun/csi-diskplugin:t1.4.3-amd64
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--node-server=true"
            - "--v=5"
            - "--alsologtostderr=true"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /data/kubelet/
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            - name: cluster-info-dir
              mountPath: /opt/app-agent/arrangement
      volumes:
        - name: registration-dir
          hostPath:
            path: /data/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /data/kubelet/plugins_registry/com.ksc.csi.diskplugin/
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /data/kubelet/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev/
        - name: cluster-info-dir
          hostPath:
            path: /opt/app-agent/arrangement
            type: Directory
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-diskplugin-sa
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-driver-registrar-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-do-driver-registrar-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: csi-diskplugin-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-do-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io