allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: essd
parameters:
  chargetype: Daily
  type: ESSD_PL0
#  zone: cn-beijing-6e
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: essd
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: essd
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: hub.kce.ksyun.com/yimenghua/nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: essd
              mountPath: /usr/share/nginx/html
      volumes:
        - name: essd
          persistentVolumeClaim:
            claimName: essd