allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
parameters:
  chargetype: Daily
  type: SSD3.0
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: Immediate