allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
parameters:
  chargetype: Daily
  type: SSD3.0
provisioner: com.ksc.csi.diskplugin
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-deployment
  labels:
    app: ssd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
  template:
    metadata:
      labels:
        app: ssd
    spec:
      containers:
        - name: nginx
          image: hub.kce.ksyun.com/yimenghua/nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: ssd1
              mountPath: /usr/share/nginx/html1
            - name: ssd2
              mountPath: /usr/share/nginx/html2
      volumes:
        - name: ssd1
          persistentVolumeClaim:
            claimName: ssd1
        - name: ssd2
          persistentVolumeClaim:
            claimName: ssd2

