apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xfs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: xfs
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-deployment
  labels:
    app: ssd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
  template:
    metadata:
      labels:
        app: ssd
    spec:
      nodeName: 12.0.3.130
      containers:
        - name: nginx
          image: hub.kce.ksyun.com/yimenghua/nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: xfs
              mountPath: /usr/share/nginx/html
      volumes:
        - name: xfs
          persistentVolumeClaim:
            claimName: xfs

