apiVersion: v1
kind: Pod
metadata:
  name: test-snapshot
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: disk-snapshot-restore
          mountPath: "/data"
  volumes:
    - name: disk-snapshot-restore
      persistentVolumeClaim:
        claimName: disk-snapshot-restore
