apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
  namespace: default
spec:
  volumeSnapshotClassName: ksyun-disk-snapshot
  source:
    persistentVolumeClaimName: disk-pvc