apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-ks3-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  # You can specify the pv name manually or just let kubernetes to bind the pv and pvc.
  volumeName: pv-ks3
  # Currently ks3 only supports static provisioning, the StorageClass name should be empty.
  storageClassName: ""