apiVersion: v1
kind: Secret
type: Opaque
metadata:
  # Replaced by your secret name.
  name: ks3-secret
  # Replaced by your secret namespace.
  namespace: kube-system
data:
  # Replaced by your temporary secret file content. You can generate a temporary secret key with these docs:
  # Note: The value must be encoded by base64.
  akId: QUtMVEZIMUNlZ0NzUjVpV1hHMm9vRlBZ
  akSecret: T0trM1J1VnIzRXEyWHRXQjVJNlJNOEp2YjY5R3BFYzNVR1JOc29QZwo=